"""Add parent_task_id to agent_tasks table

Revision ID: 4565db78e13f
Revises: 85e456a0d135
Create Date: 2025-08-08 22:30:46.029414

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4565db78e13f'
down_revision: Union[str, Sequence[str], None] = '85e456a0d135'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_tasks', sa.Column('parent_task_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'agent_tasks', 'agent_tasks', ['parent_task_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'agent_tasks', type_='foreignkey')
    op.drop_column('agent_tasks', 'parent_task_id')
    # ### end Alembic commands ###
