"""Add live_feed_id to alerts

Revision ID: 4a21c117ff93
Revises: 21eabf2f149b
Create Date: 2025-08-04 21:46:32.372630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4a21c117ff93'
down_revision: Union[str, Sequence[str], None] = '21eabf2f149b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('alerts', sa.Column('live_feed_id', sa.Integer(), nullable=False))
    op.create_index(op.f('ix_alerts_live_feed_id'), 'alerts', ['live_feed_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_alerts_live_feed_id'), table_name='alerts')
    op.drop_column('alerts', 'live_feed_id')
    # ### end Alembic commands ###
