"""Add api_key to data_sources table

Revision ID: 4e16d6d8b18e
Revises: 444443b7611c
Create Date: 2025-07-20 12:16:25.645137

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '4e16d6d8b18e'
down_revision: Union[str, Sequence[str], None] = '444443b7611c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('data_sources',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('hostname', sa.String(), nullable=False),
    sa.Column('source_type', sa.String(), nullable=False),
    sa.Column('tenant_id', sa.Integer(), nullable=False),
    sa.Column('api_key', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_data_sources_api_key'), 'data_sources', ['api_key'], unique=True)
    op.create_index(op.f('ix_data_sources_id'), 'data_sources', ['id'], unique=False)
    op.add_column('backup_jobs', sa.Column('data_source_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('backup_jobs_tenant_id_fkey'), 'backup_jobs', type_='foreignkey')
    op.create_foreign_key(None, 'backup_jobs', 'data_sources', ['data_source_id'], ['id'])
    op.drop_column('backup_jobs', 'tenant_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('backup_jobs', sa.Column('tenant_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'backup_jobs', type_='foreignkey')
    op.create_foreign_key(op.f('backup_jobs_tenant_id_fkey'), 'backup_jobs', 'tenants', ['tenant_id'], ['id'])
    op.drop_column('backup_jobs', 'data_source_id')
    op.drop_index(op.f('ix_data_sources_id'), table_name='data_sources')
    op.drop_index(op.f('ix_data_sources_api_key'), table_name='data_sources')
    op.drop_table('data_sources')
    # ### end Alembic commands ###
