"""Add error_details to agent_tasks

Revision ID: 9d68b88fc450
Revises: 4565db78e13f
Create Date: 2025-08-09 11:03:41.007348

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9d68b88fc450'
down_revision: Union[str, Sequence[str], None] = '4565db78e13f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('agent_tasks', sa.Column('error_details', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('agent_tasks', 'error_details')
    # ### end Alembic commands ###
