"""Add role and tenant linking to users

Revision ID: f251e843d1b7
Revises: 4e16d6d8b18e
Create Date: 2025-07-29 19:31:12.904630

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f251e843d1b7'
down_revision: Union[str, Sequence[str], None] = '4e16d6d8b18e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('tenants_owner_id_fkey'), 'tenants', type_='foreignkey')
    op.add_column('users', sa.Column('tenant_id', sa.Integer(), nullable=False))
    op.create_foreign_key(
        'fk_users_tenant_id',
        'users', 
        'tenants', 
        ['tenant_id'], 
        ['id']
    )
    # ### end Alembic commands ###


# Replace the entire old downgrade() function with this one

def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - adjusted for robustness ###

    # This was the old line, we keep its logic but make it explicit
    op.create_foreign_key('tenants_owner_id_fkey', 'tenants', 'users', ['owner_id'], ['id'])
    
    # This is the corrected drop command, using the explicit name
    op.drop_constraint('fk_users_tenant_id', 'users', type_='foreignkey')
    
    # This line is fine as is
    op.drop_column('users', 'tenant_id')
    
    # ### end Alembic commands ###